services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"

  tests:
    build: .
    container_name: fastapi_tests
    command: sh -c "pytest -v && pytest --cov=app tests/"
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - app